TECHNOLOGY('advanced-material-processing'):add_prereq('angels-components-construction-2'):remove_prereq('py-science-pack-mk01')
    TECHNOLOGY('angels-components-mechanical-2'):remove_pack('logistic-science-pack'):remove_prereq('logistic-science-pack')
    TECHNOLOGY('electric-mining-drill'):add_prereq('angels-components-mechanical-2'):remove_prereq('py-science-pack-mk01')
    TECHNOLOGY('fluid-processing-machines-1'):add_prereq('angels-components-construction-2'):remove_prereq('py-science-pack-mk01')
    TECHNOLOGY('crusher-2'):add_prereq('angels-components-construction-2'):remove_prereq('py-science-pack-mk01')
    TECHNOLOGY('py-burner'):add_prereq('angels-components-construction-2'):remove_prereq('py-science-pack-mk01')