
require('prototypes/multi-mod/prototypes/buildings/basic-ddc')
require('prototypes/omni-mods/prototypes/buildings/burner-soil-extractor')
require('prototypes/omni-mods/prototypes/buildings/burner-washer')
require('prototypes/omni-mods/prototypes/buildings/burner-wpu')
require('prototypes/omni-mods/prototypes/buildings/fwf-mk00')
require('prototypes/omni-mods/prototypes/buildings/seaweed-crop-mk00')
require('prototypes/omni-mods/prototypes/buildings/micro-mine-mk00')
require('prototypes/omni-mods/prototypes/buildings/research-center-mk00')
require('prototypes/omni-mods/prototypes/buildings/sap-extractor-mk00')
require('prototypes/omni-mods/prototypes/buildings/botanical-nursery-mk00')
require('prototypes/omni-mods/prototypes/buildings/moss-farm-mk00')
require('prototypes/omni-mods/prototypes/buildings/hpf-mk00')
require('prototypes/omni-mods/prototypes/buildings/fbreactor-mk00')
require('prototypes/omni-mods/prototypes/buildings/pulp-mill-mk00')
require('prototypes/omni-mods/prototypes/buildings/glassworks-mk00')