
--replaceing vanilla circuits with bobs
fun.ingredient_replace("distilator", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("classifier", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("hpf", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("tar-processing-unit", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("soil-extractormk01", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("fts-reactor", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("washer", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("fawogae-plantation", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("ulric-corral", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("solid-separator", "advanced-circuit", "basic-circuit-board")
fun.ingredient_replace("automated-factory-mk01", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("borax-mine", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("ralesia-plantation", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("jaw-crusher", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("sand-extractor", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("botanical-nursery", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("chemical-science-pack", "copper-cable", "insulated-cable")
fun.ingredient_replace("circuit-board", "ferric-chloride-solution", "boric-acid")
fun.ingredient_replace("superior-circuit-board", "gold-plate", "nexelit-plate")
fun.ingredient_replace("superior-circuit-board", "ferric-chloride-solution", "boric-acid")
fun.ingredient_replace("multi-layer-circuit-board", "ferric-chloride-solution", "boric-acid")

--replace ingrediants
fun.ingredient_replace("borax-mine","transport-belt","basic-transport-belt")
fun.ingredient_replace("borax-mine","iron-gear-wheel","steel-bearing")
fun.ingredient_replace("distilator","pipe", "copper-pipe")
fun.ingredient_replace("gasturbinemk02","pipe", "bronze-pipe")
fun.ingredient_replace("methanol-reactor","iron-gear-wheel", "steel-bearing")
fun.ingredient_replace("power-house","iron-gear-wheel", "steel-bearing")
fun.ingredient_replace("evaporator","iron-plate", "steel-gear-wheel")
fun.ingredient_replace("evaporator","iron-gear-wheel", "steel-bearing")
fun.ingredient_replace("tar-processing-unit","pipe", "stone-pipe")
fun.ingredient_replace("cooling-tower-mk01","pipe", "copper-pipe")
fun.ingredient_replace("cooling-tower-mk02","pipe", "copper-pipe")
fun.ingredient_replace("olefin-plant","iron-gear-wheel", "steel-bearing")
fun.ingredient_replace("ground-borer","iron-gear-wheel", "titanium-bearing")
fun.ingredient_replace("fts-reactor","iron-gear-wheel", "steel-bearing")
fun.ingredient_replace("ulric-corral","iron-gear-wheel", "steel-bearing")
fun.ingredient_replace("solid-separator","iron-gear-wheel", "steel-gear-wheel")
fun.ingredient_replace("classifier","iron-stick", "brass-gear-wheel")
fun.ingredient_replace("ralesia-plantation","pipe", "steel-pipe")
fun.ingredient_replace("sand-extractor","iron-gear-wheel", "brass-gear-wheel")
fun.ingredient_replace("flying-robot-frame","steel-plate", "niobium-plate")
fun.ingredient_replace("gasturbinemk02","iron-plate", "invar-alloy")
fun.ingredient_replace("power-house","iron-plate", "lead-plate")
fun.ingredient_replace("evaporator","steel-plate", "lead-plate")
fun.ingredient_replace("cooling-tower-mk01","iron-plate", "bronze-alloy")
fun.ingredient_replace("cooling-tower-mk02","iron-plate", "brass-alloy")
fun.ingredient_replace("desulfurizator-unit","iron-plate", "invar-alloy")
fun.ingredient_replace("ground-borer","iron-plate", "titanium-plate")
fun.ingredient_replace("fts-reactor","iron-plate", "invar-alloy")
fun.ingredient_replace("advanced-foundry-mk01","iron-plate", "titanium-plate")
fun.ingredient_replace("advanced-foundry-mk01","steel-plate", "invar-alloy")
fun.ingredient_replace("jaw-crusher","steel-plate", "invar-alloy")
fun.ingredient_replace("methanol-from-syngas","iron-plate", "zinc-plate")
fun.ingredient_replace("equipment-chassi","copper-plate", "bronze-alloy")
fun.ingredient_replace("glass-core","steel-plate", "silver-plate")
fun.ingredient_replace("nichrome","iron-plate", "nickel-plate")
fun.ingredient_replace("hydrogen-peroxide","iron-plate", "nickel-plate")
fun.ingredient_replace("empty-gas-canister","copper-plate", "brass-alloy")
fun.ingredient_replace("empty-gas-canister","steel-plate", "aluminium-plate")
fun.ingredient_replace("zinc-chloride","iron-plate", "zinc-plate")
fun.ingredient_replace("fts-reactor","stone-brick", "glass")
fun.ingredient_replace("advanced-foundry-mk01","concrete", "glass")
fun.ingredient_replace("ralesia-plantation","stone", "glass")
fun.ingredient_replace("flask","iron-plate", "glass")
fun.ingredient_replace("lens","stone", "glass")
fun.ingredient_replace("glass-core","sand", "glass")
fun.ingredient_replace("cladding","sand", "glass")
fun.ingredient_replace("alumina","bauxite-ore", "crushed-bauxite")
fun.ingredient_replace("lead-oxide","lead-ore", "crushed-lead")
fun.ingredient_replace("tpa","copper-ore", "cobalt-ore")
fun.ingredient_replace("tailings-classification","copper-ore", "lead-ore")
fun.ingredient_replace("tailings-classification","iron-ore", "tin-ore")
fun.ingredient_replace("methanol-reactor", "chemical-plant", "electrolyser")
fun.ingredient_replace("tailings-pond", "pump", "water-pump")
fun.ingredient_replace("olefin-plant", "chemical-plant", "electrolyser")
fun.ingredient_replace("glycerol-hydrogen", "water", "liquid-air")
fun.ingredient_replace("zinc-chloride", "water", "hydrogen-chloride")
fun.ingredient_replace("active-carbon", "water", "nitrogen")
fun.ingredient_replace("lithium-peroxide", "water", "lithia-water", 300)
fun.ingredient_replace("gasoline", "gasoline", "water", "hydrogen", 200)
fun.ingredient_replace("olefin", "water", "hydrogen", 600)
fun.ingredient_replace("anthraquinone", "steam", "liquid-air")
fun.ingredient_replace("niobium-oxide", "water", "nitrogen-dioxide")
fun.ingredient_replace("niobium-oxide","nitrogen","nitrogen-dioxide")
fun.ingredient_replace("ralesia", "water", "hydrogen")
fun.ingredient_replace("diborane", "water", "hydrogen")
fun.ingredient_replace("oleochemicals-distilation", "water", "oxygen")
fun.ingredient_replace("oleo-gasification", "water", "oxygen")
fun.ingredient_replace("tar-gasification", "water", "liquid-air")
fun.ingredient_replace("ppd", "water", "hydrogen")
fun.ingredient_replace("aromatics2", "water", "hydrogen")
fun.ingredient_replace("niobium-complex", "water", "hydrogen-chloride")
fun.ingredient_replace("tpa", "steam", "liquid-air")
fun.ingredient_replace("niobium-plate", "coal", "salt")
fun.ingredient_replace("sulfur-crudeoil", "iron-ore", "salt")
fun.ingredient_replace("nichrome", "water", "nitrogen")
fun.ingredient_replace("aromatics-to-rubber", "plastic-bar", "rubber")
fun.ingredient_replace("nas-battery", "copper-ore", "sodium-hydroxide")
fun.ingredient_replace("soda-ash", "ppd", "sodium-hydroxide")
fun.ingredient_replace("vpulp3", "petroleum-gas", "nitrogen-dioxide")
fun.ingredient_replace("vpulp3","ammonia","nitrogen-dioxide")
fun.ingredient_replace("vpulp-precip","ammonia","nitrogen-dioxide")
fun.ingredient_replace("agitator", "iron-plate", "glass")
fun.ingredient_replace("agitator", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("thickener", "electronic-circuit", "basic-circuit-board")
fun.ingredient_replace("thickener", "pipe", "brass-alloy")
fun.ingredient_replace("hydrocyclone", "iron-gear-wheel", "titanium-bearing")

--need to adjust replacer to take a table or a string
		--(FIX THIS)--
if not mods["angelspetrochem"] then
	fun.ingredient_replace("mixer", "iron-gear-wheel", "titanium-bearing")
	fun.ingredient_replace("mixer", "iron-plate", "titanium-plate")
else
	fun.ingredient_replace("mixer", "iron-gear-wheel", "cobalt-steel-bearing")
	fun.ingredient_replace("mixer", "iron-plate", "cobalt-steel-alloy")
end
fun.ingredient_replace("diamond-mine", "iron-plate", "titanium-plate")
fun.ingredient_replace("regolite-mine", "iron-plate", "tungsten-plate")
fun.ingredient_replace("jig", "pipe", "titanium-pipe")
fun.ingredient_replace("centrifugal-pan", "pipe", "titanium-pipe")
fun.ingredient_replace("compressor", "iron-gear-wheel", "titanium-bearing")
fun.ingredient_replace("genlab", "iron-gear-wheel", "nitinol-bearing")
fun.ingredient_replace("gas-separator", "pipe", "stone-pipe")
fun.ingredient_replace("molybdenum-concentrate", "water", "nitrogen-dioxide")
fun.ingredient_replace("molybdenum-concentrate","nitrogen","nitrogen-dioxide")
fun.ingredient_replace("phytoplankton", "crushed-iron", "crushed-tin")
fun.ingredient_replace("super-alloy", "steel-plate", "nickel-plate")
fun.ingredient_replace("cool-air", "pressured-air", "liquid-nitrogen")
fun.ingredient_replace("kmauts-ration", "iron-plate", "tin-plate")
fun.ingredient_replace("nexelit-matrix", "wood", "resin")
fun.ingredient_replace("nbti-alloy", "steel-plate", "titanium-plate")
fun.ingredient_replace("sc-wire", "iron-plate", "tin-plate")
fun.ingredient_replace("coil-core", "copper-cable", "gilded-copper-cable")
fun.ingredient_replace("boron-carbide", "coke", "carbon")
fun.ingredient_replace("lead-container", "iron-plate", "lead-plate")
fun.ingredient_replace("science-coating", "steel-plate", "titanium-plate")
fun.ingredient_replace("agzn-alloy", "iron-plate", "silver-plate")
fun.ingredient_replace("agzn-alloy", "stone", "zinc-plate")
fun.ingredient_replace("silver-foam", "water", "hydrogen-chloride")
fun.ingredient_replace("module-circuit-board", 'phenolic-board','phenolicboard')
fun.ingredient_replace("sub-denier-microfiber","ammonia","nitrogen-dioxide")
fun.ingredient_replace("phosphate-glass", 'glass-fiber', 'crushed-quartz')
fun.ingredient_replace('small-lamp', 'basic-circuit-board', 'copper-plate')
fun.ingredient_replace('construction-robot-ht', 'construction-robot', 'bob-construction-robot-4')
fun.ingredient_replace('logistic-robot-ht', 'logistic-robot', 'bob-logistic-robot-4')
fun.ingredient_replace('high-flux-core', 'liquid-pure-air', 'liquid-nitrogen')
fun.ingredient_replace('diode-core', 'liquid-pure-air', 'liquid-nitrogen')
fun.ingredient_replace('capacitor-termination', 'boric-acid', 'liquid-nitrogen')
fun.ingredient_replace('carbon-aerogel', 'syngas', 'nitrogen')
fun.ingredient_replace('superconductor', 'liquid-helium', 'liquid-nitrogen')

--add ingredient
fun.add_ingredient("advanced-circuit", {name = "optical-fiber", amount = 2})
fun.add_ingredient("fibreglass-board", {name = "glass", amount = 2})
fun.add_ingredient("ball-mill-mk01", {name = "steel-bearing-ball", amount = 1000})
fun.add_ingredient("botanical-nursery", {name = "glass", amount = 10})
fun.add_ingredient("filtration-media", {name = "glass", amount = 5})
fun.add_ingredient("laser-turret", {name = "lens", amount = 1})
fun.add_ingredient("combustion-olefin", {type = "fluid", name = "hydrogen", amount = 150})
fun.add_ingredient("ref-to-light-oil", {type = "fluid", name = "hydrogen", amount = 250})
fun.add_ingredient("active-carbon", {name = "sodium-hydroxide", amount = 7})
fun.add_ingredient("jaw-crusher", {name = "rubber", amount = 10})

fun.add_ingredient("molybdenum-oxide", {type = "fluid", name = "oxygen", amount = 100})
fun.add_ingredient("bio-reactor", {name = "glass", amount = 50})
fun.add_ingredient("nmf", {name = "glass", amount = 50})
fun.add_ingredient("genlab", {name = "glass", amount = 50})
fun.add_ingredient("molybdenum-plate", {type = "fluid", name = "hydrogen", amount = 100})
fun.add_ingredient("helium", {type = "fluid", name = "hydrogen", amount = 10})
fun.add_ingredient("sc-unit", {type = "fluid", name = "liquid-nitrogen", amount = 100})
fun.add_ingredient("boron-mixture", {name = "aluminium-plate", amount = 5})
fun.add_ingredient("boron", {type = "fluid", name = "hydrogen-chloride", amount = 500})
fun.add_ingredient("blanket", {name = "lead-plate", amount = 40})
fun.add_ingredient("centrifugal-pan", {name = "tungsten-plate", amount = 20})
fun.add_ingredient("compressor", {name = "tungsten-plate", amount = 20})
fun.add_ingredient("fusion-reactor-mk01", {name = "glass", amount = 200})
fun.add_ingredient("sodium-chlorate", {name = "salt", amount = 20})
fun.add_ingredient("grease", {name = "lithium", amount = 15})
fun.add_ingredient("nbti-alloy", {type = "fluid", name = "nitrogen", amount = 150})
fun.add_ingredient("ferrite", {name = "zinc-plate", amount = 10})
fun.add_ingredient("sc-wire", {name = "glass", amount = 12})
fun.add_ingredient("blanket", {name = "lithium", amount = 10})
fun.add_ingredient("blanket", {name = "tungsten-plate", amount = 40})
fun.add_ingredient("silicon-wafer", {name = 'crushed-quartz', amount = 2})
fun.add_ingredient("nano-wires", {name = 'crushed-gold', amount = 10})
fun.add_ingredient("robot-brain-logistic", {name = "paramagnetic-material", amount = 1})
fun.add_ingredient("robot-brain-logistic", {name = "inductor2", amount = 5})
fun.add_ingredient("robot-brain-construction", {name = "paramagnetic-material", amount = 1})
fun.add_ingredient("robot-brain-construction", {name = "diode", amount = 3})
fun.add_ingredient("robot-brain-logistic-2", {name = "capacitor2", amount = 3})
fun.add_ingredient("robot-brain-logistic-2", {name = "inductor2", amount = 5})
fun.add_ingredient("robot-brain-logistic-2", {name = "diamagnetic-material", amount = 1})
fun.add_ingredient("robot-brain-construction-2", {name = "capacitor2", amount = 5})
fun.add_ingredient("robot-brain-construction-2", {name = "diode", amount = 3})
fun.add_ingredient("robot-brain-construction-2", {name = "diamagnetic-material", amount = 1})
fun.add_ingredient("robot-brain-logistic-3", {name = "capacitor3", amount = 3})
fun.add_ingredient("robot-brain-logistic-3", {name = "diode3", amount = 5})
fun.add_ingredient("robot-brain-logistic-3", {name = "processor", amount = 2})
fun.add_ingredient("robot-brain-logistic-3", {name = "superconductor-servomechanims", amount = 1})
fun.add_ingredient("robot-brain-construction-3", {name = "inductor3", amount = 5})
fun.add_ingredient("robot-brain-construction-3", {name = "resistor3", amount = 5})
fun.add_ingredient("robot-brain-construction-3", {name = "processor", amount = 1})
fun.add_ingredient("robot-brain-construction-3", {name = "superconductor-servomechanims", amount = 1})
fun.add_ingredient("robot-brain-logistic-4", {name = "supercapacitor", amount = 3})
fun.add_ingredient("robot-brain-logistic-4", {name = "csle-diode", amount = 5})
fun.add_ingredient("robot-brain-logistic-4", {name = "hyperelastic-material", amount = 1})
fun.add_ingredient("robot-brain-construction-4", {name = "fault-current-inductor", amount = 3})
fun.add_ingredient("robot-brain-construction-4", {name = "paradiamatic-resistor", amount = 5})
fun.add_ingredient("robot-brain-construction-4", {name = "hyperelastic-material", amount = 1})

--remove ingredient
RECIPE("zinc-chloride"):rem_ing("copper-plate")
RECIPE("sodium-chlorate"):remove_ingredient('sodium-chlorate', 'water-saline')
		
--replace result
fun.results_replacer("aromatics-to-rubber", "crude-oil", "rubber", 1)
fun.results_replacer("glycerol-hydrogen", "petroleum-gas", {type = "fluid", name = "hydrogen", amount = 300})
fun.results_replacer("refsyngas-from-meth","water",{type = "fluid", name = "hydrogen", amount = 30})
fun.results_replacer("refsyngas-from-meth-canister","water",{type = "fluid", name = "hydrogen", amount = 30})
fun.results_replacer("aromatics","water",{type = "fluid", name = "hydrogen", amount = 100})
fun.results_replacer("cobalt-solvent","ash", "cobalt-ore", 5)
fun.results_replacer("calcinate-separation","iron-ore", "quartz", 1) --, probability = 0.6)
fun.results_replacer("calcinate-separation","copper-ore", "lead-ore", 1) --, probability = 0.3)
fun.results_replacer("molybdenum-oxide","sulfur",{type = "fluid", name = "sulfur-dioxide", amount = 50})
fun.results_replacer("liquid-rich-gas-distilation","water",{type = "fluid", name = "liquid-nitrogen", amount = 10})

--add result
fun.add_result("ash-separation", {name = "cobalt-ore", amount = 3}) --, probability = 0.3})
fun.add_result("zinc-chloride", {type = "fluid", name = "hydrogen", amount = 20})
fun.add_result("calcinate-separation",{name = "zinc-ore", amount = 1}) --, probability = 0.3})
fun.add_result("calcinate-separation",{name = "silver-ore", amount = 1}) --, probability = 0.3})
fun.add_result("sodium-chlorate", {type = "fluid", name = "hydrogen", amount = 150})
fun.add_result("cool-air", {type = "fluid", name = "nitrogen", amount = 200})
fun.add_result("liquid-air-distilation", {type = "fluid", name = "nitrogen", amount = 2})
fun.add_result("liquid-air-distilation", {type = "fluid", name = "oxygen", amount = 2})
fun.add_result("d2o-distilation", {type = "fluid", name = "oxygen", amount = 5})
fun.add_result("purier-helium", {type = "fluid", name = "liquid-nitrogen", amount = 1})
fun.add_result("sodium-chlorate", {type = "fluid", name = "hydrogen", amount = 150})

log(serpent.block(data.raw["bob-resin-wood"]))

--update result
--[[
fun.Patch
	{
		name = "bob-resin-wood",
		results = 
			{
				{name = "resin", amount = "+2"}
			}
	}
]]--	

--global replacement
fun.global_item_replacer("basic-circuit-board","pcb1")
fun.global_item_replacer("circuit-board","pcb2")
fun.global_item_replacer("superior-circuit-board","pcb3")
fun.global_item_replacer("electronic-circuit","cm-electronic-circuit")
fun.global_item_replacer("advanced-circuit","cm-advanced-circuit")
fun.global_item_replacer("processing-unit","cm-processing-unit")
fun.global_item_replacer("advanced-processing-unit","intelligent-unit")

--tech recipe add
RECIPE("gilded-copper-cable"):add_unlock('nano-tech')

--tech recipe removal

RECIPE("electronic-circuit"):remove_unlock("electronics")
RECIPE("basic-electronic-components"):remove_unlock("electronics")
RECIPE("silicon-plate"):remove_unlock("basic-electronics")
RECIPE("silicon-plate"):remove_unlock("silicon-processing")
RECIPE("phenolic-board"):remove_unlock("advanced-electronics")
RECIPE("electronic-components"):remove_unlock("advanced-electronics")
RECIPE("intergrated-electronics"):remove_unlock("advanced-electronics-2")
RECIPE("fibreglass-board"):remove_unlock("advanced-electronics-2")
RECIPE("superior-circuit-board"):remove_unlock("advanced-electronics-2")
RECIPE("circuit-board"):remove_unlock("advanced-electronics")
RECIPE("advanced-circuit"):remove_unlock("advanced-electronics")
RECIPE("advanced-logic-board"):remove_unlock("advanced-electronics-2")
RECIPE("processing-electronics"):remove_unlock("advanced-electronics-3")
RECIPE("gilded-copper-cable"):remove_unlock("advanced-electronics-3")
RECIPE("advanced-processing-unit"):remove_unlock("advanced-electronics-3")
RECIPE("multi-layer-circuit-board"):remove_unlock("advanced-electronics-3")
RECIPE("module-processor-board-3"):remove_unlock("advanced-electronics-3")
RECIPE("module-processor-board-2"):remove_unlock("advanced-electronics-2")
RECIPE("module-processor-board"):remove_unlock("modules")
RECIPE("silicon-nitride"):remove_unlock("ceramics")
RECIPE("bob-silicon-plate"):remove_unlock("silicon-processing")
RECIPE("silicon-plate2"):remove_unlock("silicon-processing")
RECIPE("silicon-wafer"):remove_unlock("silicon-processing")

--disable recipes
RECIPE("wooden-board"):set_enabled(false)
RECIPE("basic-circuit-board"):set_enabled(false)
RECIPE("wood-board"):set_enabled(false)